/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javagradle.lib.nexus.using;

import javagradle.lib.nexus.Library;

public class App {
    public String getGreeting() {

        Library classeLib = new Library();
        System.out.println("MARI usando lib que retorna true: " + classeLib.someLibraryMethod());

        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
